services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_APP_API_BASE_URL=${VITE_APP_API_BASE_URL:-/api}
      - VITE_APP_API_PROTOCOL=${VITE_APP_API_PROTOCOL:-http}
      - VITE_APP_API_HOST=${VITE_APP_API_HOST:-localhost}
      - VITE_APP_API_SERVICE_PORT=${VITE_APP_API_SERVICE_PORT:-80}
    command: pnpm run dev -- --host
